[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/demoWeb-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/"
healthcheckTimeout = 100

[deploy.env]
JAVA_OPTS = "-Xmx512m -Xms256m"
PORT = "8080" 