[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "java -jar app.jar"

[deploy.env]
DATABASE_URL = "${DATABASE_URL}"
PGUSER = "${PGUSER}"
PGPASSWORD = "${PGPASSWORD}"
SPRING_PROFILES_ACTIVE = "prod"
SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT = "30000"
SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE = "5"
SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT = "5000"
SPRING_DATASOURCE_HIKARI_LEAK_DETECTION_THRESHOLD = "60000" 