[build]
builder = "nixpacks"
buildCommand = "./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -jar target/demoWeb-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure"
restartPolicyMaxRetries = 10

[deploy.env]
JAVA_OPTS = "-Xmx512m -Xms256m" 