[build]
builder = "nixpacks"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -jar target/demoWeb-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/"
healthcheckTimeout = 100

[deploy.env]
JAVA_OPTS = "-Xmx512m -Xms256m"
PORT = "8080"

[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.install]
cmds = ["mvn dependency:go-offline"]

[phases.build]
cmds = ["mvn clean package -DskipTests"] 