[build]
builder = "nixpacks"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -jar target/demoWeb-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/"
healthcheckTimeout = 100

[deploy.env]
JAVA_OPTS = "-Xmx512m -Xms256m"
PORT = "8080"
RAILWAY_STATIC_URL = "https://demoWeb-production.up.railway.app" 