[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "java -jar app.jar"

[deploy.env]
PGHOST = "${PGHOST}"
PGPORT = "${PGPORT}"
PGDATABASE = "${PGDATABASE}"
PGUSER = "${PGUSER}"
PGPASSWORD = "${PGPASSWORD}"
SPRING_PROFILES_ACTIVE = "prod"
SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT = "30000"
SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE = "5" 