[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./railway.sh"

[deploy.env]
# Database connection
DATABASE_URL = "postgresql://postgres:idLjPfQxfiurxHKZBhNoNFibjYVHvQFt@postgres.railway.internal:5432/railway"
PGUSER = "postgres"
PGPASSWORD = "idLjPfQxfiurxHKZBhNoNFibjYVHvQFt"
PGHOST = "postgres.railway.internal"
PGPORT = "5432"
PGDATABASE = "railway"

# Application settings
PORT = "8080"
SPRING_PROFILES_ACTIVE = "cloud"

# Connection pool settings
SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT = "60000"
SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE = "5"
SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT = "5000"
SPRING_DATASOURCE_HIKARI_LEAK_DETECTION_THRESHOLD = "60000"

# Debug settings
RAILWAY_ENVIRONMENT = "production"
RAILWAY_DEBUG = "true" 